// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARm87z_Shk8-VHGna7UK3feC9vy-0F7P4',
    appId: '1:823094452434:web:44ec8a25ca8d52a4d54d0b',
    messagingSenderId: '823094452434',
    projectId: 'nexttask-2711',
    authDomain: 'nexttask-2711.firebaseapp.com',
    storageBucket: 'nexttask-2711.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVr_zncKR_060xZ-5zx6ozjn80lC6-4Y8',
    appId: '1:823094452434:android:08f1fb6e1a357fe5d54d0b',
    messagingSenderId: '823094452434',
    projectId: 'nexttask-2711',
    storageBucket: 'nexttask-2711.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj6JYoPi0TaBuIJr-3wcyTxnUi3NxRUqc',
    appId: '1:823094452434:ios:0e3a3561b5b2ca51d54d0b',
    messagingSenderId: '823094452434',
    projectId: 'nexttask-2711',
    storageBucket: 'nexttask-2711.appspot.com',
    iosClientId: '823094452434-gsgjpjghs75u0shdh7i5n0voaac2tco6.apps.googleusercontent.com',
    iosBundleId: 'com.nextgen.task',
  );
}
